services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: attractions
      POSTGRES_USER: IvanNikolaev
      POSTGRES_PASSWORD: testPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U IvanNikolaev -d attractions"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/attractions
      SPRING_DATASOURCE_USERNAME: IvanNikolaev
      SPRING_DATASOURCE_PASSWORD: testPassword
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge